name = "webhook-relay-worker"
main = "packages/worker/server.js"
compatibility_date = "2024-07-01"

account_id = "${CF_ACCOUNT_ID}"
workers_dev = false #  Set to false because using custom domain

[[deployments]]
environment = "production"
zone_id = "${CF_ZONE_ID}"
routes = [
  { pattern = "https://${CF_DOMAIN}/*", script = "webhook-relay-worker" }
]
