name = "webhook-relay-worker"
main = "dist/worker.js"
compatibility_date = "2024-07-01"

account_id = "${CF_ACCOUNT_ID}"
workers_dev = false
send_metrics = true

[[env.production]]
zone_id = "${CF_ZONE_ID}"
routes = [
  { pattern = "https://${CF_DOMAIN}/*", script = "webhook-relay-worker" }
]

[env.production.vars]
RELAY_ROUTES = "${RELAY_ROUTES}"
